AWSTemplateFormatVersion: 2010-09-09
Description: micro-list-serverless Certs

Parameters: 
  WebsiteDomain:
    Type: String
    Description: The root domain (e.g. cnn.com) of the website
  WebsiteHost:
    Type: String
    Description: The website host (e.g. www.cnn.com) for the website

Outputs:
  ZoneWildcardCertificateId:
    Value: !Ref ZoneWildcardCertificate
  ZoneRootCertificateId:
    Value: !Ref ZoneWildcardCertificate

Resources:
  ZoneWildcardCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${WebsiteDomain}"

  ZoneRootCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref WebsiteDomain
