AWSTemplateFormatVersion: 2010-09-09
Description: micro-list-serverless Master Stack
Outputs:
  UiStackId:
    Value: !Ref UiStack
  UiBucketName:
    Value: !GetAtt UiStack.Outputs.SiteBucketId
  UiUrl:
    Value: !GetAtt UiStack.Outputs.SiteBucketWebsiteUrl
  StorageStackId:
    Value: !Ref StorageStack
  ApiStackId:
    Value: !Ref ApiStack
  DnsStackId:
    Value: !Ref DNSStack
  ApiUrl:
    Value: !GetAtt ApiStack.Outputs.GraphqlApiUrl
Resources:
  CertsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./certs.yml
      Parameters:
        WebsiteDomain: micro-serverless.com
        WebsiteHost: www.micro-serverless.com
  UiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ui.yml
      Parameters:
        WebsiteDomain: micro-serverless.com
        WebsiteHost: www.micro-serverless.com
        ZoneRootCertificateId: !GetAtt CertsStack.Outputs.ZoneRootCertificateId
        ZoneWildcardCertificateId: !GetAtt CertsStack.Outputs.ZoneWildcardCertificateId
  DNSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dns.yml
      Parameters:
        CloudfrontDistributionDomainName: !GetAtt UiStack.Outputs.CloudfrontDistributionDomainName
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./storage.yml
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
    Properties:
      TemplateURL: ./api.yml
      Parameters:
        DataAccessPolicyArn: !GetAtt StorageStack.Outputs.DataAccessPolicyArn
        ServicesTableName: !GetAtt StorageStack.Outputs.ServicesTableName
