AWSTemplateFormatVersion: 2010-09-09
Description: micro-list-serverless UI

Outputs:
  SiteBucketId:
    Value: !Ref SiteBucket
  SiteBucketWebsiteUrl:
    Value: !GetAtt SiteBucket.WebsiteURL

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref WebsiteDomain
      WebsiteConfiguration:
        IndexDocument: index.html
        # Hack: redirect errors to index.html to work with react-router
        ErrorDocument: index.html

  WebsiteCloudfrontLoggingBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['-', [ !Ref WebsiteDomain, 'logs' ] ]
    DependsOn: SiteBucket

  WebsiteCloudfrontDistribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
          DistributionConfig:
              Aliases:
                  - !Ref WebsiteHost
              Comment: "Distribution CDN for site"
              DefaultCacheBehavior:
                  Compress: true
                  ForwardedValues:
                      QueryString: false
                      Cookies:
                          Forward: "none"
                  TargetOriginId: "website"
                  ViewerProtocolPolicy: "redirect-to-https"
              DefaultRootObject: "index.html"
              Enabled: true
              HttpVersion: "http2"
              IPV6Enabled: true
              Logging:
                  Bucket: !Join ['.', [!Ref WebsiteCloudfrontLoggingBucket, 's3.amazonaws.com' ] ]
              Origins:
                  -
                      DomainName: !Join ['.', [!Ref SiteBucket, 's3-website-us-east-1.amazonaws.com' ] ]
                      Id: "website"
                      CustomOriginConfig:
                          HTTPPort: 80
                          OriginProtocolPolicy: http-only
              ViewerCertificate:
                  AcmCertificateArn: !Ref ZoneWildcardCertificate
                  SslSupportMethod: "sni-only"


